name: Build and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    environment: 'PRODUCTION'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ vars.GO_VERSION }}

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests with coverage
      run: make test

    - name: Upload coverage to GitHub summary
      run: |
        go tool cover -func=coverage.out > coverage.txt
        cat coverage.txt
        echo '### Coverage Report' >> $GITHUB_STEP_SUMMARY
        cat coverage.txt >> $GITHUB_STEP_SUMMARY

    - name: Build binaries
      run: make build

    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: bin/*

