name: Deploy All Lambdas

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy

    - name: Build binaries
      run: make build

    - name: Deploy binaries
      run: |
        for f in bin/*; do
          name=$(basename "$f")
          zipfile="${name}.zip"
          zip -j "$zipfile" "$f"
          aws lambda update-function-code --function-name "$name" --zip-file "fileb://$zipfile"
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: your-region

